### ISSUE TITLE
大佬，右下角的卡通人物是如何添加的呢

### ISSUE THREAD

**Issue by TigerLiv** [pengqiangsheng/halcon#1]

**Comment by pengqiangsheng** [comment]
别叫大佬，我是菜鸡，小菜鸡。。

**Comment by TigerLiv** [comment]
卡通人物是怎么添加的  我也没法选中看。。

**Comment by pengqiangsheng** [comment]
这个叫做live-2d，你去github搜索，有很多，原理你可以试着了解，然后直接告诉你怎么使用，在我的源码中不是有一个config.js文件里面有配置。

具体路径：https://github.com/pengqiangsheng/halcon/blob/master/docs/.vuepress/config.js

在第72行

**Comment by pengqiangsheng** [comment]
没法选中是因为，这个是canvas绘画的。

**Comment by TigerLiv** [comment]
好的 ，多谢多谢
